### ISSUE TITLE
Discussion: Writing to non-container Influx

### ISSUE THREAD

**Issue by andygodber** [eargollo/smartthings-influx#19]
Me again ;)  it looks like the small issues I raised are being overcome, and the fully container-ised solution works.

Is there a way to have the main SmartThings code write to my existing InfluxDB?
(I have a load of other useful information that I would like to keep in one place)

**Comment by eargollo** [comment]
Hello, I am glad the fully containerized solution worked. 

You can change the configuration to point to your existing InfluxDB address and port (https://github.com/eargollo/smartthings-influx/blob/master/docker-compose-config.yaml#L9). And you can comment the Influx part of the docker compose (https://github.com/eargollo/smartthings-influx/blob/master/docker-compose.yml#L12-L21) so it doesn't bring up an InfluxDB.

Let me know if that works.
