### ISSUE TITLE
Re-opening: Docker image not working - monitoring component exits

### ISSUE THREAD

**Issue by andygodber** [eargollo/smartthings-influx#20]
Sorry for the confusion, but I dont think the Docker image is working afterall.
The Grafana, Influx and Chronograf are fine.

But the Monitor does not seem to work, and no data is being posted to the database.

It closes with smartthings_monitor_1 exited with code 1
and
exec /app: exec format error

I had confused everybody by saying I could see data being populated - actually, this was coming from my orginal (codersaur) smart app which was clever enough to find any InfluxDB, whether container or local!

**Comment by eargollo** [comment]
What is the result you get when you run `docker run eargollo/smartthings-influx`?

**Comment by andygodber** [comment]
Both commands come up with the same message:

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /app: exec format error

**Comment by eargollo** [comment]
Ahhh I see. I haven't built an image for arm. This is likely the reason it doesn't work.

One option is for you to build the executable locally. All you need is Golang and the cloned repo. This will depend on how tech-savvy you are. But if you clone the repo and install Golang, all you need to do is to run `go build .` and you will get an executable that works for your platform.

I will check out on how to create an arm image and let you know.

**Comment by andygodber** [comment]
Thanks for your continued help with this - Ive done the local executable, and that works.
However, my knowledge of hacking Docker images has reached its limit!
I dont know how to get the executable back into an image/container, so will wait for your exploration.

A suggestion - is there any way to change the frequency at which the monitor refresh runs? Maybe make it a parameter along with the others in smartthings-inlfux.yaml?

It looks to be about every two minutes or so, but I couldnt see anything in the code where it is mentioned.

**Comment by eargollo** [comment]
I managed to build and publish an amd64 image. Can you try the docker compose again? 

You will need to first pull the new image:
```
docker-compose pull
```

Then you can run `docker-compose up` and this time it should work.

The thing I don't understand is why the previous compose that would build an image locally didn't work for you. 

Could you also test this command from the base of the cloned repo:
```
docker-compose -f docker-compose-dev.yml up --build
```

**Comment by andygodber** [comment]
Thanks for your work on this - i *think* its now working. The Monitor image stays up, with data being logged there, and also in the stack database,
I'll continue to monitor for a while, and also redirect to the local database.

By the way - am I correct in thinking the PERIOD variable in the config file is actually the one that changes the polling frequency? I played about with it  and put it down to 10 and it gives me the granularity I was used to.

**Comment by eargollo** [comment]
Yes. Period is the polling frequency in seconds. If you want 10 minutes you need to put 600 in it.
