### ISSUE TITLE
ERROR: could not list devices: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by whiteduck22** [eargollo/smartthings-influx#26]
Hello - having trouble running the main docker compose.

I've done some debug and shared it here: https://community.smartthings.com/t/release-influxdb-logger/64919/99?u=whiteduck

```
monitor_1     | Using config file: /.smartthings-influx.yaml
monitor_1     | 2023/01/14 12:06:07 ERROR: could not list devices: invalid character '<' looking for beginning of value
```

The following commands all work OK
sudo docker run -v $PWD/.smartthings-influx.yaml:/.smartthings-influx.yaml  eargollo/smartthings-influx list
sudo docker run -v $PWD/.smartthings-influx.yaml:/.smartthings-influx.yaml  eargollo/smartthings-influx monitor (except cannot write the DB as it's not available outside of the docker compose)
sudo docker run -v $PWD/.smartthings-influx.yaml:/.smartthings-influx.yaml  eargollo/smartthings-influx status

I get some warnings from grafana too
```
grafana_1     | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana_1     | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
grafana_1     | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```
I suspect the first error is some meta data in my setup that is muddling the json parser, the second error is odd as I am running as sudo...   anyway I am not a developer so if you are able to take a look that would be appreciated!  Thank you!

**Comment by whiteduck22** [comment]
Turns out to be this
Well that's odd - even though APITOKEN was set and I checked root was seeing it with sudo echo $APITOKEN - but I had to add it into docker-compose.yml

**The other minor issue with permissions on /var/lib remains.**

**Comment by whiteduck22** [comment]
I managed to fix the perms by setting the local data directory permissions to my user.

**Comment by eargollo** [comment]
Thanks for bringing this one up. I have had a similar issue with the APITOKEN as an env var and ended up putting the token at the file directly even though it is unsafer.

I will try to find some time to add a note at the README about the issue and fix.
