### ISSUE TITLE
Can't configure Carbon Monoxide Detector

### ISSUE THREAD

**Issue by mariusmoo** [eargollo/smartthings-influx#33]
I have some combination Smoke and Carbon Monoxide detectors connected to SmartThings. However, I can't get them to work properly with smartthings-influx.

A typical entry for one of them from `smartthings-influx status` is:

```
12: Smoke/CO Garage (First Alert Smoke Detector and Carbon Monoxide Alarm (ZCOMBO)): {"components":{"main":{"battery":{"battery":{"timestamp":"2023-01-18T16:45:34.316Z","unit":"%","value":92}},"carbonMonoxideDetector":{"carbonMonoxide":{"timestamp":"2020-01-24T17:33:41.705Z","value":"clear"}},"refresh":{},"smokeDetector":{"smoke":{"timestamp":"2021-12-28T03:34:18.782Z","value":"clear"}}}}}
```

My YAML resembles this:

```
monitor:
  - battery
  - carbonMonoxideDetector
  - smokeDetector
  - switch
  - temperatureMeasurement
  - relativeHumidityMeasurement
period: 120
influxurl: [REDACTED]
influxuser: [REDACTED]
influxpassword: [REDACTED]
influxdatabase: [REDACTED]
valuemap:
  switch:
    off: 0
    on: 1
  smoke:
    clear: 0
    present: 1
  carbonMonoxide:
    clear: 0
    present: 1
```

However, in the logs I see this:
```
2023/02/06 13:22:16 26: Monitoring 'smokeDetector' from device 'Smoke/CO Garage' ([UUID-REDACTED])
2023/02/06 13:22:16 Key is smoke value {2021-12-28 03:34:18.782 +0000 UTC  clear} number value 0.000000
2023/02/06 13:22:16 27: Monitoring 'battery' from device 'Smoke/CO Garage' ([UUID-REDACTED])
2023/02/06 13:22:16 Key is battery value {2023-01-18 16:45:34.316 +0000 UTC % 92} number value 92.000000
2023/02/06 13:22:16 28: Monitoring 'carbonMonoxideDetector' from device 'Smoke/CO Garage' ([UUID-REDACTED])
2023/02/06 13:22:16 ERROR: could not convert to number there is no value map for metric 'carbonMonoxide' and value 'clear', can't convert
```

If I comment out `carbonMonoxideDetector` in the `monitor` section, it works fine. What I would like is to include monitoring for CO.

**Comment by eargollo** [comment]
Interesting. From what I saw in your message, you have the right configuration and it actually works for the smoke value.

Let me take a look. I will try to write a test with your exact data and see if I can reproduce the error. I will let you know.

**Comment by eargollo** [comment]
Ha... I believe I know the issue. Somehow, capital letters don't work on yaml setting, only on values. As a remediation I will do a lowercase comparison at the value map and this should fix the issue.

**Comment by eargollo** [comment]
Just published a fix for this issue on v0.3.1

Let me know if it worked.

**Comment by mariusmoo** [comment]
Confirmed that it works - thanks for taking care of it.

**Comment by wndrbuster** [comment]
Is there any chance we could get a new compiled binaries? 

@eargollo do you have a "buy me coffee" or donation link?   

This tool has saved us and we would like to show our appreciation.

**Comment by eargollo** [comment]
Howdy. Yes, I will compile the binaries and update the releases. I will post it here as soon as I have it. 

I haven't thought of a "buy me coffee" link. Let me look into it. Anyway, glad the tool is helpful.

**Comment by eargollo** [comment]
Done. Binaries generated for most platforms: https://github.com/eargollo/smartthings-influx/releases/tag/v0.3.2

Let me know if they worked for you.

**Comment by ChrissDeejay** [comment]
Hello @eargollo, thank you for your nice work! 
Do you have any compilable/installable version for Raspbian (Debian - Raspberry Pi4B - 64bit ARM). 
I tried all available versions but without luck. 

Thank you and have a nice day.

**Comment by eargollo** [comment]
Did you test the https://github.com/eargollo/smartthings-influx/releases/download/v0.3.2/smartthings-influx_Linux_arm64.tar.gz ?

I just tested on my PI and works well.

**Comment by ChrissDeejay** [comment]
Hello, 
thank you for your reply. 
I have just tried the tar.gz that you mentioned with the following result: 
![image](https://github.com/eargollo/smartthings-influx/assets/44715090/73367c66-243e-41d2-b0cc-ae2eb42dfd78)
Am I doing something wrong?
Thank you.

**Comment by wndrbuster** [comment]
sudo apt-get install tar gzip screen wget vi pico
wget https://github.com/eargollo/smartthings-influx/releases/download/v0.3.2/smartthings-influx_Linux_arm64.tar.gz
tar xzvf smartthings-influx_Linux_arm64.tar.gz
wget https://github.com/eargollo/smartthings-influx/blob/master/.smartthings-influx.sample.yaml
mv .smartthings-influx.sample.yaml .smartthings-influx.yaml

EDIT your .smartthings-influx.yaml (VI or PICO)

screen ./smartthings-influx
CTRL-A-D to detach he instance and let it run in background.
screen -r to re-attach.

**Comment by ChrissDeejay** [comment]
![image](https://github.com/eargollo/smartthings-influx/assets/44715090/bb055a7a-4580-4aaa-a516-24765aa30763)
However I have replaced pico with nano but for vi there is no repo ... 
I hope there`s nothing wrong with my Pi OS ...

**Comment by wndrbuster** [comment]
Nano is fine.   I am just old and still call it pico.
No need for VI if you use nano to create the config file.

**Comment by ChrissDeejay** [comment]
Thank you again for your support! 
I am, on the other hand, beginner level -100 or something. :)) 
![image](https://github.com/eargollo/smartthings-influx/assets/44715090/921fc571-1a26-46af-8a37-d71a896c1c61)
