### ISSUE TITLE
Non numeric values

### ISSUE THREAD

**Issue by Jwerfel** [eargollo/smartthings-influx#8]
Thank you for creating this project. I have been using a groovy based InfluxDB logger for SmartThings and this looks like a great way to replace that.  I have the basic functionality working but I tried to add a non numeric capability value (thermostatOperatingState) and the monitor stopped working. After looking through the code it looks like you are converting all values to a float which won't work with this since it is a string. Do you have any plans to support non numeric values?  I have never worked with go so I can vaguely understand what the code is doing but I'm not confident in changing it.

Thank you

**Comment by eargollo** [comment]
Hi @Jwerfel, it is definitely feasible to add non numeric values. Do you know what type is the thermostatOperatingState?

**Comment by Jwerfel** [comment]
The options are specified here: https://developer-preview.smartthings.com/docs/devices/capabilities/capabilities-reference/#thermostatOperatingState.

There are many options for that one but heating, cooling and idle are the main ones I'm interested in.

In addition I would want to support switch (on/off), contactSensor (open/closed), lock (locked/unlocked), motionSensor(active/inactive).

I'm not experienced with go however I was able to modify the monitor.go file to add checks for some of these.  It is ugly code so I would appreciate a better solution if possible but it does work.
v := 0.0
				if key == "thermostatOperatingState" {
					if inner["value"] == "cooling" {
						v = -1.0
					} else if inner["value"] == "heating" {
						v = 1.0
					} else {
						v = 0.0
					}
				} else if key == "switch" {
					if inner["value"] == "on" {
						v = 1.0					
					} else {
						v = 0.0
					}
				} else if key == "lock" {
					if inner["value"] == "unlocked" {
						v = -1.0
					} else if inner["value"] == "locked" {
						v = 1.0
					} else {
						v = 0.0
					}
				} else {
					v = inner["value"].(float64)
				}
				// Create point
				point, err := client.NewPoint(
					key,
					map[string]string{
						"device":     dev.device,
						"component":  dev.component,
						"capability": dev.capability,
					},
					map[string]interface{}{
						//"value": inner["value"].(float64),
						"value": v,
					},
					t,
				)

**Comment by eargollo** [comment]
Got it. I was trying to understand if you were aiming to convert the values to numerical so you could plot on Grafana.

I will take a look. Feel free to do a PR with your code if you want.

**Comment by eargollo** [comment]
Hi @Jwerfel, I made the conversion configurable. 

I added the `switch` example to the configuration file. 

It did work fine for me. Let me know if it works for you.

**Comment by Jwerfel** [comment]
The change you implemented looks great!  Much cleaner than what I had done!  I'll take a look and let you know how it works.  Thanks!
